name: derma
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  rxdart: ^0.27.2
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  animated_bottom_navigation_bar: ^1.3.3
  image_picker: ^1.1.0
  curved_navigation_bar: ^1.0.3
  dropdown_button2: ^2.3.9
  page_transition: ^2.0.5
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.0
  flutter_advanced_drawer: ^1.3.6
  body_part_selector: ^0.2.0
  dotted_line: ^3.2.2
  table_calendar: ^3.0.0
  flutter_credit_card: ^4.0.1
  get_storage: ^2.0.3
  get: ^4.3.8
  date_picker_timeline: ^1.2.3
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^17.1.2
  sqflite: ^2.3.3+1
  permission_handler: ^11.3.1
  emoji_picker_flutter: ^2.2.0
  shared_preferences: ^2.2.3
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path:
  video_player: ^2.8.6
  socket_io_client: ^2.0.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic